#!/usr/bin/env python3
"""Round and exactly verify a finite-extendibility separator."""

from __future__ import annotations

import argparse
from fractions import Fraction
from pathlib import Path

from de_finetti_utils import (
    frac_to_str,
    hypergeom_value,
    load_json,
    occupancy_rows,
    read_profile_csv,
    write_json,
)


def dot(a: list[Fraction], x: list[Fraction]) -> Fraction:
    return sum((ai * xi for ai, xi in zip(a, x)), Fraction(0, 1))


def rationalize(values: list[float], max_denominator: int) -> list[Fraction]:
    return [Fraction(str(v)).limit_denominator(max_denominator) for v in values]


def verify(profile_path: str, Q: int, a: list[Fraction]) -> dict:
    q, occupations, profile = read_profile_csv(profile_path)
    vertices = occupancy_rows(Q)
    profile_score = dot(a, profile)
    vertex_scores = []
    argmax = None
    max_score = None
    for big_occ in vertices:
        vertex = [hypergeom_value(big_occ, occ) for occ in occupations]
        score = dot(a, vertex)
        vertex_scores.append(score)
        if max_score is None or score > max_score:
            max_score = score
            argmax = big_occ
    assert max_score is not None and argmax is not None
    gap = profile_score - max_score
    theta = (profile_score + max_score) / 2
    shifted = [ai - theta for ai in a]
    shifted_profile_score = dot(shifted, profile)
    shifted_vertex_scores = []
    shifted_argmax = None
    shifted_max = None
    for big_occ in vertices:
        vertex = [hypergeom_value(big_occ, occ) for occ in occupations]
        score = dot(shifted, vertex)
        shifted_vertex_scores.append(score)
        if shifted_max is None or score > shifted_max:
            shifted_max = score
            shifted_argmax = big_occ
    margin = min(shifted_profile_score, -shifted_max)
    return {
        "q": q,
        "Q": Q,
        "num_profile_coordinates": len(occupations),
        "num_vertices": len(vertices),
        "raw_profile_score": profile_score,
        "raw_max_vertex_score": max_score,
        "raw_gap": gap,
        "raw_argmax_vertex": argmax,
        "shift_theta": theta,
        "shifted_coefficients": shifted,
        "shifted_profile_score": shifted_profile_score,
        "shifted_max_vertex_score": shifted_max,
        "shifted_argmax_vertex": shifted_argmax,
        "margin": margin,
    }


def write_tex(path: str | Path, payload: dict) -> None:
    lines = [
        "% Auto-generated by scripts/rationalize_separator.py",
        "\\paragraph{Finite-extendibility separator.}",
        "For the listed occupancy coordinates, the rational affine-normalized",
        "separator has coefficients",
        "\\[",
        "(" + ", ".join(payload["separator_a_rational"]) + ").",
        "\\]",
        "It satisfies",
        "\\[",
        "\\sum_n a_n m_n = " + payload["profile_score_rational"],
        "\\]",
        "on the pseudo-profile, while every hypergeometric vertex of",
        "$E_{q,Q}$ has value at most",
        "\\[",
        payload["max_vertex_score_rational"] + ".",
        "\\]",
        "Thus the exact rational margin is",
        "\\[",
        payload["margin_rational"] + ".",
        "\\]",
    ]
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--extendibility-json", required=True)
    parser.add_argument("--profile", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--tex-out", required=True)
    parser.add_argument("--max-denominator", type=int, default=1000000)
    args = parser.parse_args()

    ext = load_json(args.extendibility_json)
    a_float = ext.get("separator_a_float")
    if not a_float:
        raise ValueError("extendibility JSON does not contain separator_a_float")
    a = rationalize([float(x) for x in a_float], args.max_denominator)
    verified = verify(args.profile, int(ext["Q"]), a)
    shifted = verified["shifted_coefficients"]
    margin = verified["margin"]
    success = margin > 0
    payload = {
        "source_extendibility_json": args.extendibility_json,
        "profile": args.profile,
        "q": verified["q"],
        "Q": verified["Q"],
        "success": success,
        "max_denominator": args.max_denominator,
        "separator_a_rational": [frac_to_str(x) for x in shifted],
        "profile_score_rational": frac_to_str(verified["shifted_profile_score"]),
        "max_vertex_score_rational": frac_to_str(verified["shifted_max_vertex_score"]),
        "margin_rational": frac_to_str(margin),
        "argmax_vertex": list(verified["shifted_argmax_vertex"]),
        "raw_gap_rational": frac_to_str(verified["raw_gap"]),
    }
    write_json(args.out, payload)
    write_tex(args.tex_out, payload)
    if not success:
        raise SystemExit("rationalized separator failed exact positive-margin check")


if __name__ == "__main__":
    main()
