#!/usr/bin/env python3
"""Rationally certify a CP finite-extendibility separator."""

from __future__ import annotations

import argparse
import sys
from fractions import Fraction
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from de_finetti_utils import frac_to_str, load_json, parse_fraction, write_json  # noqa: E402
from test_cp_extendibility import compositions, pair_entries  # noqa: E402


def dot(a: list[Fraction], b: list[Fraction]) -> Fraction:
    return sum((x * y for x, y in zip(a, b)), Fraction(0, 1))


def rationalize(values: list[float], max_denominator: int) -> list[Fraction]:
    return [Fraction(str(value)).limit_denominator(max_denominator) for value in values]


def target_from_pair_json(pair_json: str, root_type: str) -> tuple[int, list[Fraction]]:
    root = load_json(pair_json)["roots"][root_type]
    matrix = [[parse_fraction(value) for value in row] for row in root["matrix_normalized"]]
    return int(root["alphabet_size"]), [value for row in matrix for value in row]


def vertex_vector(alphabet_size: int, Q: int, occ: tuple[int, ...]) -> list[Fraction]:
    vector = [Fraction(0, 1)] * (alphabet_size * alphabet_size)
    for i, j, value in pair_entries(occ, Q):
        vector[i * alphabet_size + j] = value
    return vector


def verify_separator(
    alphabet_size: int,
    Q: int,
    target: list[Fraction],
    coeffs: list[Fraction],
) -> dict:
    target_score = dot(coeffs, target)
    min_vertex_score: Fraction | None = None
    argmin = None
    for occ in compositions(Q, alphabet_size):
        score = dot(coeffs, vertex_vector(alphabet_size, Q, occ))
        if min_vertex_score is None or score < min_vertex_score:
            min_vertex_score = score
            argmin = occ
    assert min_vertex_score is not None and argmin is not None
    margin = min(min_vertex_score, -target_score)
    return {
        "target_score": target_score,
        "min_vertex_score": min_vertex_score,
        "argmin_vertex": argmin,
        "margin": margin,
    }


def write_tex(path: Path, payload: dict) -> None:
    lines = [
        "% Auto-generated by scripts/rationalize_cp_separator.py",
        "\\paragraph{4-root complete-positivity separator.}",
        f"For root type {payload['root_type']} and $Q={payload['Q']}$, ",
        "the rational matrix $C$ satisfies",
        "\\[",
        "\\min_N \\langle C,h_N\\rangle = " + payload["min_vertex_score_rational"],
        "\\]",
        "over all occupancy vectors $N$ with $|N|=Q$, while on the projected",
        "Flagmatic pseudo-moment it has value",
        "\\[",
        payload["target_score_rational"] + ".",
        "\\]",
        "The exact certified margin is",
        "\\[",
        payload["margin_rational"] + ".",
        "\\]",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def synthetic_case(out: Path, tex_out: Path) -> None:
    alphabet_size = 3
    Q = 4
    target = [Fraction(0, 1)] * (alphabet_size * alphabet_size)
    target[1] = Fraction(1, 1)
    coeffs = [Fraction(1, 2)] * (alphabet_size * alphabet_size)
    coeffs[1] = Fraction(-1, 2)
    coeffs[3] = Fraction(3, 2)
    verified = verify_separator(alphabet_size, Q, target, coeffs)
    if verified["margin"] <= 0:
        raise AssertionError("synthetic exact separator did not verify")
    payload = {
        "root_type": "synthetic",
        "Q": Q,
        "success": True,
        "target_score_rational": frac_to_str(verified["target_score"]),
        "min_vertex_score_rational": frac_to_str(verified["min_vertex_score"]),
        "margin_rational": frac_to_str(verified["margin"]),
        "argmin_vertex_sparse": [[i, n] for i, n in enumerate(verified["argmin_vertex"]) if n],
    }
    write_json(out, payload)
    write_tex(tex_out, payload)
    print(f"self-test passed: wrote {out}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--extendibility-json", type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--tex-out", required=True, type=Path)
    parser.add_argument("--max-denominator", type=int, default=1_000_000)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        synthetic_case(args.out, args.tex_out)
        return
    if not args.extendibility_json:
        parser.error("--extendibility-json is required unless --self-test is used")

    ext = load_json(args.extendibility_json)
    coeff_float = ext.get("separator_matrix_float")
    if not coeff_float:
        raise ValueError("extendibility JSON does not contain separator_matrix_float")
    root_type = ext["root_type"]
    Q = int(ext["Q"])
    alphabet_size, target = target_from_pair_json(ext["pair_json"], root_type)
    coeffs = rationalize([float(x) for x in coeff_float], args.max_denominator)
    verified = verify_separator(alphabet_size, Q, target, coeffs)
    success = verified["margin"] > 0
    payload = {
        "source_extendibility_json": str(args.extendibility_json),
        "pair_json": ext["pair_json"],
        "root_type": root_type,
        "Q": Q,
        "alphabet_size": alphabet_size,
        "success": success,
        "max_denominator": args.max_denominator,
        "separator_matrix_rational": [frac_to_str(x) for x in coeffs],
        "target_score_rational": frac_to_str(verified["target_score"]),
        "target_score_float": float(verified["target_score"]),
        "min_vertex_score_rational": frac_to_str(verified["min_vertex_score"]),
        "min_vertex_score_float": float(verified["min_vertex_score"]),
        "margin_rational": frac_to_str(verified["margin"]),
        "margin_float": float(verified["margin"]),
        "argmin_vertex_sparse": [[i, n] for i, n in enumerate(verified["argmin_vertex"]) if n],
    }
    write_json(args.out, payload)
    write_tex(args.tex_out, payload)
    if not success:
        raise SystemExit("rationalized CP separator failed exact positive-margin verification")
    print(f"{root_type} Q={Q}: exact separator margin {payload['margin_rational']}")


if __name__ == "__main__":
    main()
